### ISSUE TITLE
Ylläpitäjä voi konfiguroida järjestelmää

### ISSUE THREAD

**Issue by Jokauppi** [Ohtuprojekti-Fintraffic/lentovaraukset#79]
### Hyväksymiskriteerit
- [x] #264 
- [x] #286 
- [x] Ylläpitäjänä voin muuttaa varausjakson pituutta
- [x] Ylläpitäjänä voin määrittää samanaikaisten varausjaksojen määrän
- [x] Globaalin konfiguraation hakeminen/käyttäminen #???
- [x] lentokenttäkohtaiset konfiguraatiot
